steps:
- id: 'get github token from secrets'
  name: eu.gcr.io/${PROJECT_ID}/github-tag:latest
  # entrypoint: 'bash'
  # args: [ '-c', 'env' ]
  secretEnv: ['GITHUB_TOKEN', 'REPO_OWNER']
availableSecrets:
  secretManager:
  - versionName: ${_GITHUB_TOKEN_SECRET}
    env: 'GITHUB_TOKEN'
  - versionName: ${_REPO_OWNER_SECRET}
    env: 'REPO_OWNER'
